CREATE TABLE CUSTOMER(
    CUST_ID BIGINT UNIQUE NOT NULL PRIMARY KEY,
    CUST_FIRSTNAME VARCHAR(30) NOT NULL,
    CUST_LASTNAME VARCHAR(30),
    CUST_BIRTHDATE TIMESTAMP,
    CUST_GENDER CHAR(1) NOT NULL,
    CUST_ADDRESS VARCHAR(50),
    CUST_CITY VARCHAR(20),
    CUST_POSTCODE CHAR(5)
);

CREATE TABLE ACCOUNT(
    ACC_NUMBER CHAR(13) UNIQUE NOT NULL PRIMARY KEY,
    ACC_OWNER BIGINT NOT NULL,
    ACC_DATE_CREATED DATE NOT NULL DEFAULT NOW(),
    ACC_BALANCE DECIMAL(10, 0) NOT NULL
);

CREATE TABLE TRANSACTION_TRANSFER(
    TRS_ID BIGINT NOT NULL PRIMARY KEY,
    TRS_TO_ACCOUNT CHAR(13) NOT NULL,
    TRS_STATUS CHAR(1) NOT NULL
);

CREATE TABLE TRANSACTION(
    TRS_ID BIGINT UNIQUE NOT NULL PRIMARY KEY,
    TRS_FROM_ACCOUNT CHAR(13) NOT NULL,
    TRS_DATE DATE NOT NULL DEFAULT NOW(),
    TRS_AMOUNT DECIMAL(10, 0) NOT NULL,
    TRS_TYPE CHAR(2) NOT NULL
);